# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl build-essential git && \
    rm -rf /var/lib/apt/lists/*

# Install Foundry tools
RUN curl -L https://foundry.paradigm.xyz | bash && \
    export PATH="$HOME/.foundry/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Ensure Foundry tools are in PATH for subsequent RUN steps
ENV PATH="/root/.foundry/bin:${PATH}"

# Install Python dependencies
RUN pip install --no-cache-dir .

# Default command (will be overridden by MCP host)
CMD ["python", "src/eth_wh_mcp/main.py"]
